version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5438:5432"



  aspnet-core-app:
    image: mcr.microsoft.com/dotnet/aspnet:7.0
    container_name: aspnet-core-app
    restart: on-failure
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["dotnet", "YourAspNetCoreApp.dll"]
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=localhost;Port=5438;Database=persons;User Id=program;Password=test;"

volumes:
  db-data: