version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: program
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: persons
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5438:5432"

  net:
    build:
      context: ./net
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=persons;Username=program;Password=test"
    depends_on:
      - postgres


volumes:
  db-data: