name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
# Устанавливаем .NET SDK 8.0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Восстанавливаем зависимости
      - name: Restore dependencies
        run: dotnet restore ./net/Lab1.sln

      # Сборка проекта
      - name: Build project
        run: dotnet build ./net --configuration Release --no-restore

      # Публикация проекта
      - name: Publish project
        run: dotnet publish ./net --configuration Release --no-build --output ./publish

      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true
